In [1]:
a = "Hello World"
b = [a.split()]
b

[['Hello', 'World']]

In [2]:
from collections import Counter
colors = ['red', 'blue', 'red', 'green', 'blue', 'blue']
c = Counter(colors)
c

Counter({'red': 2, 'blue': 3, 'green': 1})

In [3]:
print(dict(c))

{'red': 2, 'blue': 3, 'green': 1}


In [20]:
d = c.items()

In [25]:
e = sorted(d, key=lambda x:x[1], reverse=True)

In [26]:
e

[('blue', 3), ('red', 2), ('green', 1)]

In [29]:
e[0][0]

'blue'

In [8]:
t = "hhhh, eeee . ffff.cccc . ppppp. "

In [10]:
g = t.split(" . ")
g

['hhhh, eeee', 'ffff.cccc', 'ppppp. ']

In [1]:
import torch

In [2]:
a = torch.tensor([2,3,4,5,6,7])


In [3]:
a = torch.repeat_interleave(a, repeats=2, dim=0)

In [4]:
a

tensor([2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [5]:
a = torch.repeat_interleave(a, 3)
a

tensor([2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
        6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7])

In [18]:
mask = torch.arange(2,dtype = torch.float32)

In [19]:
mask

tensor([0., 1.])

In [20]:
valid = torch.arange(4,dtype = torch.float32)

In [21]:
valid

tensor([0., 1., 2., 3.])

In [22]:
t = mask[None, :] < valid[:,None]

In [23]:
t.shape

torch.Size([4, 2])

In [24]:
t

tensor([[False, False],
        [ True, False],
        [ True,  True],
        [ True,  True]])